# pyright: reportInvalidTypeForm=false,reportMissingModuleSource=false

import bpy
import re
from bpy.types import PropertyGroup
from bpy.props import StringProperty, BoolProperty, EnumProperty, FloatProperty, IntProperty, FloatVectorProperty, BoolVectorProperty

from ...Utility.PZ_UpdateMethods import *
from ...Utility.PZ_FilterMethods import filter_zombie_injuries

'''
This property group contains all properties relating to a rig's
randomization chances for things like injuries
'''

class PZ_HumanRigRandomProperties(PropertyGroup):
    random_zombie: BoolProperty(
        name='Zombie',
        default=False,
        override={"LIBRARY_OVERRIDABLE"}
    )

    random_skin_tone: BoolProperty(
        name='Random Skin Color',
        default=True,
        override={"LIBRARY_OVERRIDABLE"}
    )

    random_tint_color: BoolProperty(
        name='Random Tint Color',
        description='Randomize the tint of all tintable clothing generated by this outfit',
        default=True,
        override={"LIBRARY_OVERRIDABLE"}
    )

    static_tint_color: FloatVectorProperty(
        name="Tint Color",
        description='Tint all tintable clothing generated by this outfit with this color',
        subtype='COLOR',
        default=(1.0, 1.0, 1.0),
        min=0,
        max=1,
        override={"LIBRARY_OVERRIDABLE"}
    )

    random_hair_style: BoolProperty(
        name='Random Hair Style',
        default=True,
        override={"LIBRARY_OVERRIDABLE"}
    )

    random_hair_color: BoolProperty(
        name='Random Hair Color',
        default=True,
        override={"LIBRARY_OVERRIDABLE"}
    )
    
    natural_hair_color: BoolProperty(
        name='Natural Hair Color',
        default=True,
        override={"LIBRARY_OVERRIDABLE"}
    )

    random_beard_chance: IntProperty(
        name='Random Beard Chance',
        default=50,
        min=0,
        max=100,
        subtype='PERCENTAGE',
        override={"LIBRARY_OVERRIDABLE"}
    )

    randomize_outfit_injuries: BoolProperty(
        default=False
    )

    randomize_body_injuries: BoolProperty(
        default=True
    )

    randomize_zombie_injuries: BoolProperty(
        default=False
    )

    randomize_bloodiness: BoolProperty(
        default=True
    )

    randomize_dirtiness: BoolProperty(
        default=True
    )

    min_random_body_injuries: IntProperty(
        name='Min Body Injuries',
        default=0,
        min=0,
        max=16
    )

    max_random_body_injuries: IntProperty(
        name='Max Body Injuries',
        default=5,
        min=0,
        max=16
    )

    min_random_zombie_injuries: IntProperty(
        name='Min Zombie Injuries',
        default=0,
        min=0,
        max=72
    )

    max_random_zombie_injuries: IntProperty(
        name='Max Zombie Injuries',
        default=5,
        min=0,
        max=72
    )

    random_scratch_chance: FloatProperty(
        name='Random Scratch Chance',
        description='Weighted chance injury will be a scratch (chances are automatically evened out to add up to 100%)',
        default=65,
        subtype='PERCENTAGE',
        min=0.0,
        max=100.0,
        override={"LIBRARY_OVERRIDABLE"}
    )
    
    random_laceration_chance: FloatProperty(
        name='Random Laceration Chance',
        description='Weighted chance injury will be a laceration (chances are automatically evened out to add up to 100%)',
        default=30,
        subtype='PERCENTAGE',
        min=0.0,
        max=100.0,
        override={"LIBRARY_OVERRIDABLE"}
    )

    random_bite_chance: FloatProperty(
        name='Random Bite Chance',
        description='Weighted chance injury will be a bite (chances are automatically evened out to add up to 100%)',
        default=5,
        subtype='PERCENTAGE',
        min=0.0,
        max=100.0,
        override={"LIBRARY_OVERRIDABLE"}
    )

    random_bandage_chance: FloatProperty(
        name='Random Bandage Chance',
        description='Weighted chance injury will be covered with a bandage',
        default=35,
        subtype='PERCENTAGE',
        min=0.0,
        max=100.0,
        override={"LIBRARY_OVERRIDABLE"}
    )

    random_bloody_bandage_chance: FloatProperty(
        name='Random Bloody Bandage Chance',
        description='Weighted chance a bandage will be bloody',
        default=35,
        subtype='PERCENTAGE',
        min=0.0,
        max=100.0,
        override={"LIBRARY_OVERRIDABLE"}
    )

    part_bloodiness_chance: FloatProperty(
        name='Part Bloodiness Chance',
        description='The chance for each body part to have blood applied',
        default=50,
        subtype='PERCENTAGE',
        min=0,
        max=100
    )
    
    min_random_bloodiness: FloatProperty(
        default=0,
        min=0,
        max=5
    )

    max_random_bloodiness: FloatProperty(
        default=2,
        min=0,
        max=5
    )

    part_dirtiness_chance: FloatProperty(
        name='Part Dirtiness Chance',
        description='The chance for each body part to have dirt applied',
        default=50,
        subtype='PERCENTAGE',
        min=0,
        max=100
    )

    min_random_dirtiness: FloatProperty(
        default=0,
        min=0,
        max=2
    )

    max_random_dirtiness: FloatProperty(
        default=1,
        min=0,
        max=2
    )